### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [mcraiha/Dithery-cli#1]
Dear Kaarlo,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by mcraiha** [comment]
Hi,

Thanks for feedback. I added a GitHub action that builds Windows self-contained single binary .exe (x64), and the zipped file can be found from https://github.com/mcraiha/Dithery-cli/releases 

It is quite huge file because it contains dotnet runtime (that is why I didn't want to do these kind of releases before), but hopefully with upcoming dotnet (6.0) the file size can be decreased.
